### ISSUE TITLE
Service down

### ISSUE THREAD

**Issue by seanjsavage** [morganney/restbus#1]
Ahoy

The service is currently down.  http://restbus.info/ returns a 503 Service Temporarily Unavailable message.

**Comment by morganney** [comment]
Thanks for the heads up Sean.  Looks like there is a parse error (probably
due to some funky xml from nextbus).  I'll have to look at the logs to see
what request triggered the error.

In any event, can you do me a favor and actually grab restbus from npm and
install it on one of your servers.  If I find that people are simply using
restbus.info to get their data, I'll have to shut down the demo portion of
the site.  restbus is intended to be used as a proxy to the NextBus XML
feed running on your own server (not mine).

I need this machine for my families personal sights too.  Thanks much Sean
:)

Morgan

**Comment by seanjsavage** [comment]
Aha!  I will.  Sorry, didn't realize that... Thanks

**Comment by morganney** [comment]
Thanks Sean. I see there is script requesting many urls now, so I'm going
to shut it off for a couple hours.

If you know what request triggered the error it would help to quickly
resolve the issue?

**Comment by seanjsavage** [comment]
Hi Morgan

I'm not sure what triggered it to go down.  I have a script that just
queries predictions, in only goes for the following 8 bus lines, so if it
was on my end it was one of these.  This powers a device I made and
installed above the front door of the house where I live, telling the
people who live in the house when the nearest lines to the house are
arriving.    I will certainly figure out how to set this up on my own
server; apologies, I'm new to this and didn't realize Restbus wasn't a
public service open to be queried by anyone.  Thanks for putting it
together!

TL: 22 outbound church/duboce
http://restbus.info/api/agencies/sf-muni/routes/22/stops/4005/predictions
TR: 24 outbound castro/duboce:
http://restbus.info/api/agencies/sf-muni/routes/24/stops/4330/predictions
RT: N outbound Sunset Tunnel East Portal
http://restbus.info/api/agencies/sf-muni/routes/N/stops/7252/predictions
RB: 6/71 outbound haight/divisadero
http://restbus.info/api/agencies/sf-muni/stops/14950/predictions
BR: 24 inbound castro/duboce:
http://restbus.info/api/agencies/sf-muni/routes/24/stops/4331/predictions
BL: 22 inbound church/duboce
http://restbus.info/api/agencies/sf-muni/routes/22/stops/4006/predictions
LB: 6/71 inbound haight/divisadero
http://restbus.info/api/agencies/sf-muni/stops/14951/predictions
LT: N inbound Sunset Tunnel East Portal
http://restbus.info/api/agencies/sf-muni/routes/N/stops/7318/predictions

**Comment by morganney** [comment]
Hey Sean,

Thanks for the useful info.

What you made with the transit data sounds awesome! When I find some free
time I'll try and clean up whatever was causing the explosion. Just moved
the family to the country so it's a bit busy for me at the moment.

If you'd like some help setting up restbus one one of your servers let me
know. I can try to be of service.

Morgan

**Comment by seanjsavage** [comment]
Hi Morgan.  The documentation page is down, can't tell from the github page
how to get it running... can you send me the instructions?  Thanks

- Sean

**Comment by morganney** [comment]
Oops, forgot to restart.

**Comment by seanjsavage** [comment]
Great, got it installed.  Thanks again, I will be no further drain on your
server resources ;)

**Comment by morganney** [comment]
I'm just happy you find restbus useful :)

**Comment by seanjsavage** [comment]
Hi Morgan

The Restbus process I'm running on my friend's server now keeps crashing,
he seems to think it's stumbling on some bad XML (see below).  Have you
seen this happen on your instantiation of it? Known issue?

Thanks,

Sean

---------- Forwarded message ----------
From: Dav Yaginuma <dav.yaginuma@gmail.com>
Date: Thu, May 7, 2015 at 9:30 AM
Subject: Re: Skedu server down?
To: "Sean J. Savage" <sean@seansavage.com>


Hmm, yeah there was a crash of the restbus server code. I'll restart and
try to figure out an auto restart for it.

Looks like at some point it was trying to parse some bad XML

/home/dav/node_modules/restbus/node_modules/xml2js/node_modules/sax/lib/sax.js:912
  if (this.error) throw this.error
                            ^
Error: Unmatched closing tag: body
Line: 18
Column: 7
Char: >
    at error
(/home/dav/node_modules/restbus/node_modules/xml2js/node_modules/sax/lib/sax.js:642:8)
    at strictFail
(/home/dav/node_modules/restbus/node_modules/xml2js/node_modules/sax/lib/sax.js:662:22)
    at closeTag
(/home/dav/node_modules/restbus/node_modules/xml2js/node_modules/sax/lib/sax.js:851:5)
    at Object.write
(/home/dav/node_modules/restbus/node_modules/xml2js/node_modules/sax/lib/sax.js:1293:29)
    at Parser.exports.Parser.Parser.parseString
(/home/dav/node_modules/restbus/node_modules/xml2js/lib/xml2js.js:386:29)
    at Parser.__bind [as parseString]
(/home/dav/node_modules/restbus/node_modules/xml2js/lib/xml2js.js:6:61)
    at exports.parseString
(/home/dav/node_modules/restbus/node_modules/xml2js/lib/xml2js.js:409:19)
    at Unzip.utils.getJsFromXml.stream.on.callback.errtype
(/home/dav/node_modules/restbus/lib/utils.js:83:5)
    at Unzip.EventEmitter.emit (events.js:126:20)
    at zlib.js:349:10


On Thu, May 7, 2015 at 9:13 AM, Sean J. Savage <sean@seansavage.com> wrote:

> ...at least the restbus thing is:
> http://skeduapp.com:3000/agencies/sf-muni/routes/22/stops/4005/predictions
>



-- 
Dav ɐɯnuıƃɐ⅄

**Comment by morganney** [comment]
Hi Sean,

Thanks for the traceback. I'll use it to find a solution for dealing with
malformed xml.

If it's happening for your friend it will happen to all restbus users.

**Comment by seanjsavage** [comment]
Thanks!  Just setting it up w/ a restart daemon in the meantime to fire it
off again when it hangs up...

**Comment by morganney** [comment]
This should fix the issue discussed in this thread https://github.com/morganney/restbus/commit/2a1607b69563d07ae0048ae8ba80bcbf07412180
