### ISSUE TITLE
Location-based Predictions are inconsistent

### ISSUE THREAD

**Issue by yoshiask** [morganney/restbus#11]
The location prediction endpoint (http://restbus.info/api/locations/{lat},{lon}/predictions) returns different items every single time the request is made. Sometimes, it returns an empty JSON array, and other times it returns stops that are over 100 miles away.

**Comment by morganney** [comment]
@yoshiask I'm not sure whats up with that as it returns the data more or less as how its passed from the NextBus API. Last time I worked at NextBus (years ago) that endpoint was under development and experimental so maybe something changed. FWIW, there is a note in the [restbus docs](http://restbus.info/) for that endpoint which states:

> † This endpoint is experimental as it relies on a NextBus Inc. data source that may be removed at any time without warning or notice. Use it at your own risk.

It would take building a database of all the stops lat/lon for all the known routes for all the known agencies and then building a custom endpoint (not proxied from NextBus) to get something more consistent or better defined. I don't have the time to do that (but it sounds interesting).

When I click on the example URL for that endpoint from the restbus docs it returns the same set of data, so maybe its something unique to your lat/lon pair.
