### ISSUE TITLE
Make this usable as an express middleware

### ISSUE THREAD

**Issue by bigpopakap** [morganney/restbus#4]
Thank you so much for this! It's really great and easy to set up. I was wondering if we could make it *even easier* be allowing it to be used as a middleware to express

I would like to be able to do something like:
```
var express = require('express');
var app = express();
var restbus = require('restbus');

app.use('/restbus/api', restbus.middleware());

// now we can call this directly from other parts of the app without network calls
// see https://www.npmjs.com/package/run-middleware
require('run-middleware')(app);
app.runMiddleware('/restbus/api/agencies',function(code, body, headers) {
    console.log(body);
    // body is our JSON response
});
```

This is better than the current implementation because it would work with Heroku. The current suggestion wouldn't work because Heroku environment variables tell you the port to use, and they only support listening on one port
(Here's the current suggestion reproduced):
```
http.createServer(app).listen('3030', function() {
  console.log('app is now listening on port 3030');
  restbus.listen(function() {
    console.log('restbus is now listening on port 3535');
  });
});
```

**Comment by G2Jose** [comment]
@bigpopakap I wanted to do something similar, so I created a PR for just this!
https://github.com/morganney/restbus/pull/5

**Comment by bigpopakap** [comment]
Thanks! I didn't really look at the code, but wow that was a lot easier than I thought. I probably should have just done it... oh well. Thank you for taking the initiative!

**Comment by morganney** [comment]
Thanks for the suggestion. This has been added in [v1.2.0](https://github.com/morganney/restbus/releases/tag/1.2.0).

http://restbus.info/#middleware
