### ISSUE TITLE
service down?

### ISSUE THREAD

**Issue by dansgithubuser** [morganney/restbus#7]
http://restbus.info/api/agencies/ttc/vehicles is giving
```
{"status":500,"statusDesc":"Internal Server Error","message":"Unable to parse XML into JavaScript. No \"body\" element in NextBus XML document"}
```
Earlier today it was giving 404s. I apologize for my naivete about nextbus, I assume something is up on its side? I think other transit tracking services are working though. I'm not sure if they could be driven off other data sources.

**Comment by morganney** [comment]
Looks like [this line](https://github.com/morganney/restbus/blob/master/lib/utils.js#L88) is being hit. I'll take a look over the next couple of days...

Feel free to open a PR if you can get to it before me.

**Comment by morganney** [comment]
@dansgithubuser 
Running restbus locally everything is working fine, so I'm suspecting maybe they have blacklisted the ip for restbus.info.

You know, restbus is meant to be installed on your own servers right? You use it as a proxy to the NextBus API.

**Comment by dansgithubuser** [comment]
I didn't know this. Huh. OK, thanks for info!

**Comment by thewebman** [comment]
Works now! Thanks
